import type { Streamer } from "@/lib/types";

const baseDate = "2026-05-06T00:00:00.000Z";

export const demoStreamers: Streamer[] = [
  {
    id: "demo-hoshino-miluna",
    name: "星乃ミルナ",
    youtube_url: "https://www.youtube.com/@demo-miluna",
    thumbnails: ["https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=82"],
    categories: ["歌枠", "癒し系", "雑談"],
    tags: ["初見歓迎", "夜配信", "まったり", "歌うま"],
    description: "眠る前に少しだけ歌を届ける、星明かり系Vtuber。",
    one_liner: "眠る前に、少しだけ歌を届けます。",
    stream_time: "22時〜24時",
    plan_type: "paid",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-aoi-neon",
    name: "蒼井ネオン",
    youtube_url: "https://www.youtube.com/@demo-neon",
    thumbnails: ["https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=82"],
    categories: ["ゲーム", "参加型", "雑談"],
    tags: ["元気", "初心者歓迎", "参加型", "FPS"],
    description: "一緒に遊べるゲーム配信を中心に、毎週参加型を開催。",
    one_liner: "一緒に遊べるゲーム配信、毎週開催中！",
    stream_time: "20時〜23時",
    plan_type: "free",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-yumemi-rion",
    name: "夢見リオン",
    youtube_url: "https://www.youtube.com/@demo-rion",
    thumbnails: ["https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=900&q=82"],
    categories: ["ASMR", "癒し系", "深夜配信"],
    tags: ["睡眠導入", "落ち着く声", "深夜", "癒し"],
    description: "静かな夜に寄り添う、睡眠導入とASMRの配信者。",
    one_liner: "今日の疲れを、やさしくほどきます。",
    stream_time: "23時〜25時",
    plan_type: "boost",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-kanade-sora",
    name: "奏そら",
    youtube_url: "https://www.youtube.com/@demo-sora",
    thumbnails: ["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=82"],
    categories: ["歌枠", "弾き語り", "作業BGM"],
    tags: ["弾き語り", "透明感", "作業用", "初見歓迎"],
    description: "ギターと声でゆっくり届く、弾き語り中心のチャンネル。",
    one_liner: "弾き語りと作業BGMで、夜を少し明るく。",
    stream_time: "21時〜23時",
    plan_type: "paid",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-momose-iroha",
    name: "百瀬いろは",
    youtube_url: "https://www.youtube.com/@demo-iroha",
    thumbnails: ["https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=900&q=82"],
    categories: ["雑談", "初見歓迎", "朝活"],
    tags: ["朝活", "おしゃべり", "明るい", "コメント拾い多め"],
    description: "朝から元気を分ける、コメント多めの雑談配信。",
    one_liner: "朝の10分、元気をチャージしませんか？",
    stream_time: "7時〜9時",
    plan_type: "free",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-kuroha-nagi",
    name: "黒羽ナギ",
    youtube_url: "https://www.youtube.com/@demo-nagi",
    thumbnails: ["https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=82"],
    categories: ["ゲーム", "ホラー", "深夜配信"],
    tags: ["ホラー", "絶叫", "深夜", "リアクション"],
    description: "ホラーゲームと深夜テンションが得意なリアクション系Vtuber。",
    one_liner: "怖いのに見たくなる、深夜のホラー枠。",
    stream_time: "22時〜26時",
    plan_type: "paid",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-haruka-latte",
    name: "春風ラテ",
    youtube_url: "https://www.youtube.com/@demo-latte",
    thumbnails: ["https://images.unsplash.com/photo-1495567720989-cebdbdd97913?auto=format&fit=crop&w=900&q=82"],
    categories: ["雑談", "作業BGM", "癒し系"],
    tags: ["まったり", "作業用", "カフェ風", "癒し"],
    description: "カフェのような空気で、作業と雑談に寄り添う配信。",
    one_liner: "作業のおともに、ゆるいカフェ時間を。",
    stream_time: "14時〜17時",
    plan_type: "free",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-shirase-yuki",
    name: "白瀬ユキ",
    youtube_url: "https://www.youtube.com/@demo-yuki",
    thumbnails: ["https://images.unsplash.com/photo-1484589065579-248aad0d8b13?auto=format&fit=crop&w=900&q=82"],
    categories: ["勉強", "作業BGM", "雑談"],
    tags: ["勉強配信", "集中", "静か", "初見歓迎"],
    description: "一緒に集中する勉強・作業配信が中心。",
    one_liner: "ひとりじゃ続かない作業を、一緒に。",
    stream_time: "19時〜22時",
    plan_type: "paid",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-akatsuki-meme",
    name: "暁メメ",
    youtube_url: "https://www.youtube.com/@demo-meme",
    thumbnails: ["https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=82"],
    categories: ["企画", "雑談", "ショート"],
    tags: ["企画多め", "切り抜き歓迎", "テンポ良い", "笑える"],
    description: "短時間でも楽しめる企画と雑談が多めのチャンネル。",
    one_liner: "短時間で笑える、テンポ重視の企画枠。",
    stream_time: "18時〜21時",
    plan_type: "boost",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  },
  {
    id: "demo-nanami-ciel",
    name: "七海シエル",
    youtube_url: "https://www.youtube.com/@demo-ciel",
    thumbnails: ["https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=900&q=82"],
    categories: ["歌枠", "海外向け", "雑談"],
    tags: ["日本語", "英語少し", "歌枠", "初見歓迎"],
    description: "日本語中心、少し英語も交えながら歌と雑談を届けます。",
    one_liner: "海風みたいな歌声で、初見さんも歓迎。",
    stream_time: "20時〜24時",
    plan_type: "free",
    is_visible: true,
    impressions: 0,
    likes: 0,
    created_at: baseDate
  }
];
