// フォント定義（仕様書3.2/3.3/3.4）。5カテゴリを網羅する
// 単一ウェイトの静的OFLフォント15種を登録する（可変フォントの太さ曖昧性を避けるため）。
import type { FontConfig } from "./types";

export const FONTS: FontConfig[] = [
  {
    id: "anton",
    displayName: "Anton",
    internalFamily: "VMK Anton",
    category: "太字・インパクト",
    previewLabel: "極太で目立つ定番",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "easy",
    recommendedFor: ["インパクト重視", "短めの名前"],
    licenseFilePath: "lib/tshirt/fontfiles/Anton-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Anton-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/Anton-Regular.ttf",
  },
  {
    id: "archivo-black",
    displayName: "Archivo Black",
    internalFamily: "VMK Archivo Black",
    category: "太字・インパクト",
    previewLabel: "重厚でモダンな太字",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "easy",
    recommendedFor: ["ロゴ感", "力強い印象"],
    licenseFilePath: "lib/tshirt/fontfiles/ArchivoBlack-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/ArchivoBlack-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/ArchivoBlack-Regular.ttf",
  },
  {
    id: "alfa-slab-one",
    displayName: "Alfa Slab One",
    internalFamily: "VMK Alfa Slab One",
    category: "太字・インパクト",
    previewLabel: "極太スラブセリフ",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 14,
    weedingDifficulty: "easy",
    recommendedFor: ["レトロ", "厚みのある存在感"],
    licenseFilePath: "lib/tshirt/fontfiles/AlfaSlabOne-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/AlfaSlabOne-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/AlfaSlabOne-Regular.ttf",
  },
  {
    id: "lilita-one",
    displayName: "Lilita One",
    internalFamily: "VMK Lilita One",
    category: "かわいい・ポップ",
    previewLabel: "丸みのあるポップ体",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "easy",
    recommendedFor: ["かわいい", "親しみやすい"],
    licenseFilePath: "lib/tshirt/fontfiles/LilitaOne-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/LilitaOne-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/LilitaOne-Regular.ttf",
  },
  {
    id: "graduate",
    displayName: "Graduate",
    internalFamily: "VMK Graduate",
    category: "定番・長い名前向け",
    previewLabel: "カレッジ風の定番",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "normal",
    recommendedFor: ["長めの名前", "スポーティ"],
    licenseFilePath: "lib/tshirt/fontfiles/Graduate-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Graduate-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/Graduate-Regular.ttf",
  },
  {
    id: "righteous",
    displayName: "Righteous",
    internalFamily: "VMK Righteous",
    category: "個性的・ロゴ感",
    previewLabel: "レトロで角丸なロゴ体",
    allowedSizes: ["M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "normal",
    recommendedFor: ["ロゴ感", "個性的"],
    licenseFilePath: "lib/tshirt/fontfiles/Righteous-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Righteous-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/Righteous-Regular.ttf",
  },
  {
    id: "bungee",
    displayName: "Bungee",
    internalFamily: "VMK Bungee",
    category: "個性的・ロゴ感",
    previewLabel: "サイン看板風の縦横太字",
    allowedSizes: ["M", "L"],
    maxCharacters: 13,
    weedingDifficulty: "normal",
    recommendedFor: ["ストリート", "看板風"],
    licenseFilePath: "lib/tshirt/fontfiles/Bungee-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Bungee-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/Bungee-Regular.ttf",
  },
  {
    id: "berkshire-swash",
    displayName: "Berkshire Swash",
    internalFamily: "VMK Berkshire Swash",
    category: "筆記体・上品",
    previewLabel: "上品な筆記体",
    allowedSizes: ["M", "L"],
    maxCharacters: 12,
    minStrokeWidthMm: 1.0,
    weedingDifficulty: "advanced",
    recommendedFor: ["上品", "エレガント"],
    licenseFilePath: "lib/tshirt/fontfiles/BerkshireSwash-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/BerkshireSwash-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/BerkshireSwash-Regular.ttf",
  },
  {
    id: "oswald",
    displayName: "Oswald",
    internalFamily: "VMK Oswald",
    category: "定番・長い名前向け",
    previewLabel: "縦長のコンデンス体で長い名前も収まる",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "easy",
    recommendedFor: ["長めの名前", "すっきり定番"],
    licenseFilePath: "lib/tshirt/fontfiles/Oswald-SemiBold.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Oswald-SemiBold.ttf",
    publicFontUrl: "/tshirt-fonts/Oswald-SemiBold.ttf",
  },
  {
    id: "roboto-condensed",
    displayName: "Roboto Condensed",
    internalFamily: "VMK Roboto Condensed",
    category: "定番・長い名前向け",
    previewLabel: "読みやすいコンデンス体の定番",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "easy",
    recommendedFor: ["長めの名前", "読みやすさ重視"],
    licenseFilePath: "lib/tshirt/fontfiles/RobotoCondensed-Bold.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/RobotoCondensed-Bold.ttf",
    publicFontUrl: "/tshirt-fonts/RobotoCondensed-Bold.ttf",
  },
  {
    id: "league-spartan",
    displayName: "League Spartan",
    internalFamily: "VMK League Spartan",
    category: "定番・長い名前向け",
    previewLabel: "幾何学的でモダンな定番",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 15,
    weedingDifficulty: "easy",
    recommendedFor: ["長めの名前", "モダン"],
    licenseFilePath: "lib/tshirt/fontfiles/LeagueSpartan-Bold.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/LeagueSpartan-Bold.ttf",
    publicFontUrl: "/tshirt-fonts/LeagueSpartan-Bold.ttf",
  },
  {
    id: "fredoka",
    displayName: "Fredoka",
    internalFamily: "VMK Fredoka",
    category: "かわいい・ポップ",
    previewLabel: "まるっとやわらかいポップ体",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 14,
    weedingDifficulty: "easy",
    recommendedFor: ["かわいい", "やわらかい印象"],
    licenseFilePath: "lib/tshirt/fontfiles/Fredoka-Bold.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Fredoka-Bold.ttf",
    publicFontUrl: "/tshirt-fonts/Fredoka-Bold.ttf",
  },
  {
    id: "baloo-2",
    displayName: "Baloo 2",
    internalFamily: "VMK Baloo 2",
    category: "かわいい・ポップ",
    previewLabel: "丸みの強いにぎやかなポップ体",
    allowedSizes: ["S", "M", "L"],
    maxCharacters: 13,
    weedingDifficulty: "easy",
    recommendedFor: ["かわいい", "にぎやか"],
    licenseFilePath: "lib/tshirt/fontfiles/Baloo2-ExtraBold.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Baloo2-ExtraBold.ttf",
    publicFontUrl: "/tshirt-fonts/Baloo2-ExtraBold.ttf",
  },
  {
    id: "playball",
    displayName: "Playball",
    internalFamily: "VMK Playball",
    category: "筆記体・上品",
    previewLabel: "野球のユニフォーム風スクリプト",
    allowedSizes: ["M", "L"],
    maxCharacters: 12,
    minStrokeWidthMm: 1.0,
    weedingDifficulty: "advanced",
    recommendedFor: ["スポーティ", "チーム感"],
    licenseFilePath: "lib/tshirt/fontfiles/Playball-Regular.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/Playball-Regular.ttf",
    publicFontUrl: "/tshirt-fonts/Playball-Regular.ttf",
  },
  {
    id: "oleo-script",
    displayName: "Oleo Script",
    internalFamily: "VMK Oleo Script",
    category: "個性的・ロゴ感",
    previewLabel: "丸みのある太字スクリプト",
    allowedSizes: ["M", "L"],
    maxCharacters: 13,
    weedingDifficulty: "normal",
    recommendedFor: ["ロゴ感", "個性的"],
    licenseFilePath: "lib/tshirt/fontfiles/OleoScript-Bold.OFL.txt",
    fontFilePath: "lib/tshirt/fontfiles/OleoScript-Bold.ttf",
    publicFontUrl: "/tshirt-fonts/OleoScript-Bold.ttf",
  },
];

const FONT_BY_ID = new Map(FONTS.map((f) => [f.id, f]));

export function getFontConfig(fontId: string): FontConfig | undefined {
  return FONT_BY_ID.get(fontId);
}

export function isValidFontId(fontId: string): boolean {
  return FONT_BY_ID.has(fontId);
}
